# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - master
  - uat

pool:
  vmImage: ubuntu-latest

name: 1.0.$(rev:r)

steps:
  - script: |
      git config user.email "you@example.com" 
      git config user.name "Your Name"

  - task: NodeTool@0
    inputs:
      versionSpec: "14.x"
    displayName: Install Node.js

  - task: Npm@1
    inputs:
      command: "custom"
      customCommand: "version $(build.buildnumber)"
    displayName: npm version

  - task: Npm@1
    displayName: "npm install"
    inputs:
      command: "install"
      verbose: false
      # customRegistry: useFeed
      # customFeed: "9e9a6cab-132b-48cf-9614-0cf65dec3070"

  - task: Npm@1
    displayName: "Build Module"
    inputs:
      command: custom
      verbose: false
      customCommand: "run build"

  - task: CopyFiles@2
    inputs:
      sourceFolder: "$(Build.SourcesDirectory)/dist"
      contents: "**"
      targetFolder: $(Build.ArtifactStagingDirectory)/npm
    displayName: "Copy npm package"

  - task: CopyFiles@2
    inputs:
      sourceFolder: "$(Build.SourcesDirectory)"
      contents: "package.json"
      targetFolder: $(Build.ArtifactStagingDirectory)/npm
    displayName: "Copy package.json"

  # - task: Npm@1
  #   displayName: "Publish package"
  #   inputs:
  #     command: publish
  #     verbose: false
  #     publishRegistry: useFeed
  #     publishFeed: "9e9a6cab-132b-48cf-9614-0cf65dec3070"

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: "$(Build.ArtifactStagingDirectory)"
      ArtifactName: "drop"
